const arr = [
    {
      id: 93,
      name: 'Добавление новых сервисов',
      skillId: 'NewServices',
      description: 'Описание есть в документации',
      helpUrl: '',
      subjectName: 'Процессы',
    },
    {
      id: 94,
      name: 'Дебаггер',
      skillId: 'Debugger',
      description:
        "Подключение к процессу, установка Breakpoint'ов, хождение по стеку вызовов, значения переменных.",
      helpUrl: '',
      subjectName: 'IDE',
    },
    {
      id: 97,
      name: 'Git',
      skillId: 'IdeGit',
      description: 'Умение пользоваться гитом через IDE',
      helpUrl: '',
      subjectName: 'IDE',
    },
    {
      id: 98,
      name: 'Автоматизация задач',
      skillId: 'TaskAuto',
      description: 'Автоматизация npm скриптов через IDE',
      helpUrl: '',
      subjectName: 'IDE',
    },
    {
      id: 110,
      name: 'Rebase',
      skillId: 'Rebase',
      description: '',
      helpUrl: '',
      subjectName: 'Git',
    },
    {
      id: 121,
      name: 'Многопоточность',
      skillId: 'Multithreading',
      description: '',
      helpUrl: '',
      subjectName: 'Операционные системы',
    },
    {
      id: 122,
      name: 'Многозадачность',
      skillId: 'Multitasking',
      description: '',
      helpUrl: '',
      subjectName: 'Операционные системы',
    },
    {
      id: 123,
      name: 'Работа с памятью',
      skillId: 'Memory',
      description:
        'Как linux работает с памятью, какие виды памяти бывают и для чего используются.',
      helpUrl: '',
      subjectName: 'Операционные системы',
    },
    {
      id: 125,
      name: 'Сетевые интерфейсы',
      skillId: 'NetworkIffaces',
      description:
        'Можно почитать тут: https://www.ibm.com/docs/ru/aix/7.2?topic=protocol-tcpip-network-interfaces\nДостаточно базовой информации: ethernet, lo, для чего нужны интерфейсы.',
      helpUrl: '',
      subjectName: 'Операционные системы',
    },
    {
      id: 130,
      name: 'Алерты',
      skillId: 'Alerts',
      description:
        'Какие у нас есть алерты? Будет рандомно выбран алерт, который нужно будет объяснить.',
      helpUrl: '',
      subjectName: 'Мониторинг',
    },
    {
      id: 138,
      name: 'Варианты реализации на клиенте',
      skillId: 'ClientCache',
      description: '',
      helpUrl: '',
      subjectName: 'Кеширование',
    },
    {
      id: 139,
      name: 'Варианты реализации на сервере',
      skillId: 'ServerCache',
      description: '',
      helpUrl: '',
      subjectName: 'Кеширование',
    },
    {
      id: 140,
      name: 'Использование Redis для кеша у нас',
      skillId: 'RedisCache',
      description: 'Что кешируется? Как скинуть этот кеш?',
      helpUrl: '',
      subjectName: 'Кеширование',
    },
    {
      id: 148,
      name: 'npm: Приватные репозитории',
      skillId: 'NpmPrivateRegistry',
      description: '',
      helpUrl: '',
      subjectName: 'Пакетные менеджеры',
    },
    {
      id: 150,
      name: 'yarn',
      skillId: 'Yarn',
      description: '',
      helpUrl: '',
      subjectName: 'Пакетные менеджеры',
    },
    {
      id: 152,
      name: 'Integration',
      skillId: 'IntegrationsTests',
      description: '',
      helpUrl: '',
      subjectName: 'Тестирование',
    },
    {
      id: 165,
      name: 'Принцип работы',
      skillId: 'RedisBase',
      description: '',
      helpUrl: '',
      subjectName: 'Redis',
    },
    {
      id: 167,
      name: 'Работа с объектами',
      skillId: 'RedisObjects',
      description: '',
      helpUrl: '',
      subjectName: 'Redis',
    },
    {
      id: 169,
      name: 'TTL Ключей',
      skillId: 'RedisTTL',
      description: '',
      helpUrl: '',
      subjectName: 'Redis',
    },
    {
      id: 172,
      name: 'Бек',
      skillId: 'BackL10n',
      description: 'Использование локализации на беке',
      helpUrl: '',
      subjectName: 'Локализация',
    },
    {
      id: 187,
      name: 'Sensors',
      skillId: 'Sensors',
      description: 'Sensors - один из табов консоли',
      helpUrl: '',
      subjectName: 'Консоль разработчика',
    },
    {
      id: 188,
      name: 'Rendering',
      skillId: 'Rendering',
      description: 'Rendering - один из табов консоли',
      helpUrl: '',
      subjectName: 'Консоль разработчика',
    },
    {
      id: 193,
      name: 'Network: Throttling/Block',
      skillId: 'NetworkThrottlingBlock',
      description: '',
      helpUrl: '',
      subjectName: 'Консоль разработчика',
    },
    {
      id: 194,
      name: 'WebSocket',
      skillId: 'DevToolsWebSocket',
      description: 'Возможность чтения информации, которая гуляет по сокету.',
      helpUrl: '',
      subjectName: 'Консоль разработчика',
    },
    {
      id: 198,
      name: 'Application: Service Workers',
      skillId: 'ApplicationServiceWorkers',
      description: '',
      helpUrl: '',
      subjectName: 'Консоль разработчика',
    },
    {
      id: 221,
      name: 'Дерево',
      skillId: 'Tree',
      description: '',
      helpUrl: '',
      subjectName: 'Структуры и алгоритмы',
    },
    {
      id: 230,
      name: 'Docker: Dockerfile',
      skillId: 'Dockerfile',
      description: 'Умение написать свой Dockerfile, знание основных операторов.',
      helpUrl: '',
      subjectName: 'Среда исполнения контейнеров',
    },
    {
      id: 231,
      name: 'Images',
      skillId: 'Images',
      description:
        'Что представляют из себя образы, какая у них связь с контейнерами.',
      helpUrl: '',
      subjectName: 'Среда исполнения контейнеров',
    },
    {
      id: 232,
      name: 'CRIO',
      skillId: 'CRIOBase',
      description:
        'Что это за рантайм, кто использует. Уметь смотреть логи, запускать контейнеры и просматривать информацию о них.',
      helpUrl: '',
      subjectName: 'Среда исполнения контейнеров',
    },
    {
      id: 233,
      name: 'containerd',
      skillId: 'containerd',
      description:
        'Что это за рантайм, кто использует, основные команды для взаимодейсвия с ним',
      helpUrl: '',
      subjectName: 'Среда исполнения контейнеров',
    },
    {
      id: 234,
      name: 'Container',
      skillId: 'Container',
      description: 'Что представляет собой контейнер как самостоятельная единица',
      helpUrl: '',
      subjectName: 'Среда исполнения контейнеров',
    },
    {
      id: 290,
      name: 'Взаимодействие сервисов',
      skillId: 'ServicesInteractions',
      description: '',
      helpUrl: '',
      subjectName: 'Микросервисы',
    },
    {
      id: 291,
      name: 'Дебаг',
      skillId: 'ServiceDebug',
      description: '',
      helpUrl: '',
      subjectName: 'Микросервисы',
    },
    {
      id: 302,
      name: 'XSS',
      skillId: 'XSS',
      description: 'Что такое? Возможно ли у нас?',
      helpUrl: '',
      subjectName: 'Безопасность',
    },
    {
      id: 315,
      name: 'Symbol',
      skillId: 'JsSymbol',
      description: '',
      helpUrl: '',
      subjectName: 'Javascript',
    },
    {
      id: 320,
      name: 'Декораторы',
      skillId: 'JsDecorators',
      description: '',
      helpUrl: '',
      subjectName: 'Javascript',
    },
    {
      id: 323,
      name: 'Наследование',
      skillId: 'Inheritance',
      description: 'Через классы, прототипы',
      helpUrl: '',
      subjectName: 'Javascript',
    },
    {
      id: 326,
      name: 'Генераторы',
      skillId: 'Generators',
      description: '',
      helpUrl: '',
      subjectName: 'Javascript',
    },
    {
      id: 334,
      name: 'Самостоятельность',
      skillId: 'Independence',
      description:
        'Можешь самостоятельно разбираться в любом коде/проблеме/библиотеке/баге. ',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 337,
      name: 'Тайм-менеджмент',
      skillId: 'TimeManagement',
      description:
        'Программист должны уметь управлять своим временем. Как прокачать: ведение задач в ютрек+детальная декомпозиция с оценкой estimation time + 7 навыков высокоэффективных людей. ',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 338,
      name: 'Эмоциональный интеллект',
      skillId: 'EmotionalInt',
      description:
        'Все люди разные, необходимо уметь чувствовать настроение других и не позволять себе крайне эмоционировать. ',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 340,
      name: 'Ведение переговоров',
      skillId: 'Negotiating',
      description: 'Способность предлагать и отстаивать свои решения.',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 342,
      name: 'Проактивность',
      skillId: 'Proactivity',
      description:
        'Очень важно наперед продумывать функцию/процесс. Делать больше, чем ожидается. Быть заинтересованным в результате в разрезе бизнесовых и/или технических показателей. ',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 343,
      name: 'Умение аргументировать свои решения',
      skillId: 'DecisionsArgs',
      description: '',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 346,
      name: 'Ориентир на конечный для пользователя функционал',
      skillId: 'GuideUserEnd',
      description:
        'Думать о том как пользователь будет использовать какую-либо функцию продукта. Если вам кажется что предлагаемое ТЗ или дизайн не является удобным/полезным, то надо об этом сказать. Программист должен представлять, что он сам будет пользоваться этим продуктом. ',
      helpUrl: '',
      subjectName: 'Soft',
    },
    {
      id: 385,
      name: 'Компоненты высшего порядка',
      skillId: 'HOC',
      description: '',
      helpUrl: '',
      subjectName: 'React',
    },
    {
      id: 395,
      name: 'Virtual DOM',
      skillId: 'ShadowDOM',
      description: 'Как работает, зачем нужен. ',
      helpUrl: '',
      subjectName: 'React',
    },
  ];
  
  const res = arr.reduce((acc, { name, subjectName }) => {
    if (subjectName !== 'Soft') {

      if (!acc[subjectName]) {
        acc[subjectName] = [];
      }

      acc[subjectName].push(name)
    }

    return acc;
  }, {});

  console.log(res);
  